# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpoints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='mass',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='saturated_fat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='sugar',
            field=models.FloatField(),
        ),
    ]
